# Project: CanevasAPI
# Makefile created by Dev-C++ 4.9.9.2

CPP  = g++.exe
CC   = gcc.exe
WINDRES = windres.exe
RES  = ../../../../../../../temp/CanevasAPI_private.res
OBJ  = ../../../../../../../temp/Principal.o ../../../../../../../temp/Evenements.o ../../../../../../../temp/Geometrie.o ../../../../../../../temp/Initialisation.o ../../../../../../../temp/Global.o ../../../../../../../temp/InitialisationGL.o ../../../../../../../temp/GlobalWin.o ../../../../../../../temp/bitmap2.o ../../../../../../../temp/matriceombre.o ../../../../../../../temp/mur.o ../../../../../../../temp/normal.o ../../../../../../../temp/texture2.o $(RES)
LINKOBJ  = ../../../../../../../temp/Principal.o ../../../../../../../temp/Evenements.o ../../../../../../../temp/Geometrie.o ../../../../../../../temp/Initialisation.o ../../../../../../../temp/Global.o ../../../../../../../temp/InitialisationGL.o ../../../../../../../temp/GlobalWin.o ../../../../../../../temp/bitmap2.o ../../../../../../../temp/matriceombre.o ../../../../../../../temp/mur.o ../../../../../../../temp/normal.o ../../../../../../../temp/texture2.o $(RES)
LIBS =  -L"C:/Dev-Cpp/lib" -mwindows -lopengl32 -lglu32  
INCS =  -I"C:/Dev-Cpp/include" 
CXXINCS =  -I"C:/Dev-Cpp/include/c++"  -I"C:/Dev-Cpp/include"  -I"C:/Dev-Cpp/include/dx8" 
BIN  = CanevasAPI.exe
CXXFLAGS = $(CXXINCS)  
CFLAGS = $(INCS)   
RM = rm -f

.PHONY: all all-before all-after clean clean-custom

all: all-before CanevasAPI.exe all-after


clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o "CanevasAPI.exe" $(LIBS)

../../../../../../../temp/Principal.o: Principal.cpp
	$(CPP) -c Principal.cpp -o ../../../../../../../temp/Principal.o $(CXXFLAGS)

../../../../../../../temp/Evenements.o: Evenements.cpp
	$(CPP) -c Evenements.cpp -o ../../../../../../../temp/Evenements.o $(CXXFLAGS)

../../../../../../../temp/Geometrie.o: Geometrie.cpp
	$(CPP) -c Geometrie.cpp -o ../../../../../../../temp/Geometrie.o $(CXXFLAGS)

../../../../../../../temp/Initialisation.o: Initialisation.cpp
	$(CPP) -c Initialisation.cpp -o ../../../../../../../temp/Initialisation.o $(CXXFLAGS)

../../../../../../../temp/Global.o: Global.cpp
	$(CPP) -c Global.cpp -o ../../../../../../../temp/Global.o $(CXXFLAGS)

../../../../../../../temp/InitialisationGL.o: InitialisationGL.cpp
	$(CPP) -c InitialisationGL.cpp -o ../../../../../../../temp/InitialisationGL.o $(CXXFLAGS)

../../../../../../../temp/GlobalWin.o: GlobalWin.cpp
	$(CPP) -c GlobalWin.cpp -o ../../../../../../../temp/GlobalWin.o $(CXXFLAGS)

../../../../../../../temp/bitmap2.o: bitmap2.cpp
	$(CPP) -c bitmap2.cpp -o ../../../../../../../temp/bitmap2.o $(CXXFLAGS)

../../../../../../../temp/matriceombre.o: matriceombre.cpp
	$(CPP) -c matriceombre.cpp -o ../../../../../../../temp/matriceombre.o $(CXXFLAGS)

../../../../../../../temp/mur.o: mur.cpp
	$(CPP) -c mur.cpp -o ../../../../../../../temp/mur.o $(CXXFLAGS)

../../../../../../../temp/normal.o: normal.cpp
	$(CPP) -c normal.cpp -o ../../../../../../../temp/normal.o $(CXXFLAGS)

../../../../../../../temp/texture2.o: texture2.cpp
	$(CPP) -c texture2.cpp -o ../../../../../../../temp/texture2.o $(CXXFLAGS)

../../../../../../../temp/CanevasAPI_private.res: CanevasAPI_private.rc MesRessources.rc 
	$(WINDRES) -i CanevasAPI_private.rc --input-format=rc -o ../../../../../../../temp/CanevasAPI_private.res -O coff 
