//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SpilinEditor.rc
//
#define IDD_ABOUTBOX                    100
#define ID_VIEW_PREVIEWBAR              101
#define IDS_PROPSHT_CAPTION             103
#define IDD_PROPPAGE1                   104
#define IDD_PROPPAGE2                   105
#define IDD_PROPPAGE3                   106
#define IDD_PROPPAGE4                   107
#define CG_IDR_POPUP_SPILIN_EDITOR_VIEW 108
#define ID_STATO_RUOTA                  111
#define ID_STATO_SCALA                  112
#define IDR_MAINFRAME                   128
#define IDR_SPILINTYPE                  129
#define ID_INDICATOR_STEPS              129
#define IDC_LINK_CURSOR                 130
#define ID_INDICATOR_NODI               130
#define ID_INDICATOR_POLYGONS           131
#define IDD_VRML_OPTIONS                132
#define IDB_LOGO_BITMAP                 134
#define IDC_CUR_ROTATE                  135
#define IDD_KEY_HELP                    136
#define IDC_CUR_SCALE                   136
#define IDD_KEY_HELP1                   137
#define IDC_CUR_ZOOM                    137
#define IDR_PREVIEWBAR                  138
#define IDC_CUR_CREA                    141
#define IDC_CUR_MODIF                   142
#define IDD_SETTINGS_DLG                142
#define IDC_CUR_INSER                   143
#define IDC_MAILTO_CURSOR               144
#define IDC_CUR_PREVIEW                 145
#define IDC_COLOR_DIFFUSE               1001
#define IDC_COLOR_SPECULAR              1002
#define IDC_COLOR_EMITTED               1003
#define IDC_TAB1                        1003
#define IDC_SEZIONI                     1004
#define IDC_DRAWPOLYG_CHECK             1004
#define IDC_STEPS                       1005
#define IDC_FL_POS                      1005
#define IDC_FL_N                        1006
#define IDC_SHININESS                   1007
#define IDC_FL_NO                       1007
#define IDC_PTYPE_COMBO                 1007
#define IDC_TRANSPARENCY                1008
#define IDC_FL_SE                       1008
#define IDC_CREASE                      1009
#define IDC_FL_S                        1009
#define IDC_RAGGIO                      1010
#define IDC_FL_SO                       1010
#define IDC_VERSO                       1011
#define IDC_PENSIZE_EDIT                1011
#define IDC_FL_E                        1011
#define IDC_FL_O                        1012
#define IDC_SPIN2                       1013
#define IDC_BL_POS                      1013
#define IDC_PROPORTIONAL_EDIT           1013
#define IDC_SPIN3                       1014
#define IDC_BL_N                        1014
#define IDC_SPIN4                       1015
#define IDC_CURVESTEPS_EDIT             1015
#define IDC_BL_NO                       1015
#define IDC_SPIN5                       1016
#define IDC_PENSIZE_SPIN                1016
#define IDC_BL_SE                       1016
#define IDC_GRIDSIZE_SPIN               1017
#define IDC_BL_S                        1017
#define IDC_COLOR_DIFF                  1018
#define IDC_CURVESTEP_SPIN              1018
#define IDC_BL_SO                       1018
#define IDC_COLOR_EMES                  1019
#define IDC_3DSTEPS_EDIT                1019
#define IDC_BL_E                        1019
#define IDC_COLOR_SPEC                  1020
#define IDC_3DSTEPS_SPIN                1020
#define IDC_BL_O                        1020
#define IDC_OBJCOLOR_SWATCH             1021
#define IDC_OBJ_BACKCULL                1022
#define IDC_SECTIONS_SPIN               1023
#define IDC_EXTRUSION_SPIN              1024
#define IDC_OBJNAME_EDIT                1025
#define IDC_GRIDSIZE_EDIT               1026
#define IDC_CONIC_CHECK                 1026
#define IDC_OPEN_CHECK                  1027
#define IDC_STURM_CHECK                 1028
#define IDC_ALTEZ_EDIT                  1029
#define IDC_SECTIONS_EDIT               1030
#define IDC_ALTEZ_SPIN                  1030
#define IDC_BLCOLOR_SWATCH              1031
#define IDC_PROPORTIONAL_SPIN           1031
#define IDC_EXTRUSION_EDIT              1032
#define IDC_GPCOLOR_SWATCH              1032
#define IDC_OBJ_SMOOTH                  1033
#define IDC_FLCOLOR_SWATCH              1034
#define IDC_BGCOLOR_SWATCH              1035
#define IDC_PENCOLOR_SWATCH             1038
#define IDC_GRIDCOLOR_SWATCH            1039
#define IDC_3DBGCOLOR_SWATCH            1039
#define IDC_NORMALIZE_RADIO             1040
#define IDC_PROPORTIONAL_RADIO          1041
#define IDC_AUTHOR_LINK                 1042
#define IDC_HOME_LINK                   1043
#define ID_MODIFICA_CHIUDISPLINE        32771
#define ID_VISUAL_REDRAW                32773
#define ID_STATO_MIRROR_X               32774
#define ID_STATO_MIRROR_Y               32775
#define ID_STATO_SELECT                 32776
#define ID_PIUSTEPS                     32777
#define ID_MENOSTEPS                    32778
#define ID_VIEW_GRIDPLANE               32779
#define ID_EDIT_SELECT_NONE             32780
#define ID_FILE_ESPORTAINPOV            32781
#define ID_FILE_ESPORTAINVRML20         32782
#define ID_SNAP                         32783
#define ID_STATO_CREA                   32784
#define ID_STATO_MODIFICA               32785
#define ID_STATO_INSER                  32786
#define ID_SETTINGS                     32787
#define ID_FLIP_N                       32789
#define ID_SMOOTH_SHADE                 32790
#define ID_REVOLUTION                   32792
#define ID_ESTRUSION                    32793

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32780
#define _APS_NEXT_CONTROL_VALUE         1000
#define _APS_NEXT_SYMED_VALUE           103
#endif
#endif
